/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Classes.AlunoIterator;
import Classes.Aluno_has_EtapaIterator;
import Classes.AlunosHasEtapa;
import Classes.Cafe;
import Classes.CafeIterator;
import Classes.Etapa;
import Classes.EtapaIterator;
import Classes.SalaIterator;
import Classes.Salas;
import DBConnect.MySQLcon;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bene
 */
public class ConsultaAluno extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaAluno
     */
    public ConsultaAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TFnome = new javax.swing.JTextField();
        BtConsulta = new javax.swing.JButton();
        Btfecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTresultado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de Aluno");

        jLabel1.setText("Nome Contendo");

        TFnome.setText("fulano");

        BtConsulta.setText("Consultar");
        BtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtConsultaActionPerformed(evt);
            }
        });

        Btfecha.setText("Fechar Janela");
        Btfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtfechaActionPerformed(evt);
            }
        });

        JTresultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Sala", "Etapa", "Cafe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTresultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btfecha)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TFnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtConsulta)
                    .addComponent(Btfecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtConsultaActionPerformed
        MySQLcon con = new MySQLcon();
        String sql = "SELECT pkAluno, NomeCompleto, Cafe_pkcafe FROM Alunos where NomeCompleto LIKE ?";
        ResultSet rsAluno = null;
        try{
            PreparedStatement prepstatement = con.preparaSQL(sql);
            prepstatement.setString(1, "%"+TFnome.getText()+"%");
            rsAluno = con.ler();
        }catch(Exception e){
            
        }
        
        AlunoIterator alunoiterator = new AlunoIterator();
        Cafe cafe = new Cafe();
        CafeIterator cafeiterator = new CafeIterator();
        AlunosHasEtapa alunoHasEtapa;
        Aluno_has_EtapaIterator alunoHasEtapaIterator = new Aluno_has_EtapaIterator();
        Salas sala;
        SalaIterator salaiterator = new SalaIterator();
        Etapa etapa;
        EtapaIterator etapaiterator = new EtapaIterator();
        int pkAluno = 0;
        String Nome = "";
        String Cafe = "";
        String Sala = "";
        String Etapa = "";
        try{
            DefaultTableModel model;
            model = (DefaultTableModel)JTresultado.getModel();
            for (int i = model.getRowCount() - 1; i >= 0; i--) {
                model.removeRow(i);
            }
            while (rsAluno.next()){
                pkAluno = rsAluno.getInt(1);
                Nome = rsAluno.getString(2);
                Cafe = "";
                Sala= "";
                Etapa = "";
                if  (!rsAluno.getString("Cafe_pkcafe").isEmpty()){
                    cafe = cafeiterator.buscacafePelaPk(rsAluno.getInt("Cafe_pkcafe"));
                    Cafe = cafe.getDescricao();
                }
                alunoHasEtapa = alunoHasEtapaIterator.buscaLigaçãoPeloAluno(rsAluno.getInt("pkAluno"));
                if  (!(alunoHasEtapa.fkAluno == -1)){
                    sala = salaiterator.buscaSalaPelaPk(alunoHasEtapa.fkSala);
                    Sala = sala.getDescrição();
                    etapa = etapaiterator.buscaEtapaPelaPk(alunoHasEtapa.fkEtapa);
                    Etapa = etapa.getDescricao();
                }
                
                model.addRow(new Object[]{pkAluno, Nome, Sala,Etapa,Cafe});
        }
        }catch(Exception e){
            
        }
        con.close();
    }//GEN-LAST:event_BtConsultaActionPerformed

    private void BtfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtfechaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BtfechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtConsulta;
    private javax.swing.JButton Btfecha;
    private javax.swing.JTable JTresultado;
    private javax.swing.JTextField TFnome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
