/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
/**
 *
 * @author Bene
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MIalunos = new javax.swing.JMenuItem();
        MISalas = new javax.swing.JMenuItem();
        MIcafe = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MIConsultaAluno = new javax.swing.JMenuItem();
        MIConsultaSala = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de evento");

        jMenu1.setText("Cadastros");

        MIalunos.setText("Alunos");
        MIalunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIalunosActionPerformed(evt);
            }
        });
        jMenu1.add(MIalunos);

        MISalas.setText("Sala de Eventos");
        MISalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MISalasActionPerformed(evt);
            }
        });
        jMenu1.add(MISalas);

        MIcafe.setText("Área do café");
        MIcafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIcafeActionPerformed(evt);
            }
        });
        jMenu1.add(MIcafe);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        MIConsultaAluno.setText("Aluno");
        MIConsultaAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConsultaAlunoActionPerformed(evt);
            }
        });
        jMenu2.add(MIConsultaAluno);

        MIConsultaSala.setText("Café");
        MIConsultaSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIConsultaSalaActionPerformed(evt);
            }
        });
        jMenu2.add(MIConsultaSala);

        jMenuItem1.setText("Salas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Distribuir");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Distribuidor de Alunos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MISalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MISalasActionPerformed
        // TODO add your handling code here:
        CadEvento cadastrosala = new CadEvento();
        cadastrosala.setVisible(true);
    }//GEN-LAST:event_MISalasActionPerformed

    private void MIalunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIalunosActionPerformed
        // TODO add your handling code here:
        CadAluno cadastroaluno = new CadAluno();
        cadastroaluno.setVisible(true);
    }//GEN-LAST:event_MIalunosActionPerformed

    private void MIcafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIcafeActionPerformed
        // TODO add your handling code here:
        CadCafe cadastrocafe = new CadCafe();
        cadastrocafe.setVisible(true);
    }//GEN-LAST:event_MIcafeActionPerformed

    private void MIConsultaAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConsultaAlunoActionPerformed
        // TODO add your handling code here:
        ConsultaAluno cAluno = new ConsultaAluno();
        cAluno.setVisible(true);
    }//GEN-LAST:event_MIConsultaAlunoActionPerformed

    private void MIConsultaSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIConsultaSalaActionPerformed
        // TODO add your handling code here:
        ConsultaCafe ccafe = new ConsultaCafe();
        ccafe.setVisible(true);
    }//GEN-LAST:event_MIConsultaSalaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ConsultaSala cSala = new ConsultaSala();
        cSala.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DistribuirAlunos dAlunos = new DistribuirAlunos();
        dAlunos.setVisible(true);     
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MIConsultaAluno;
    private javax.swing.JMenuItem MIConsultaSala;
    private javax.swing.JMenuItem MISalas;
    private javax.swing.JMenuItem MIalunos;
    private javax.swing.JMenuItem MIcafe;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables
}
